const products = [
    {
      id: 1,
      name: "Smartphone X12",
      prevPrice: 799,
      currPrice: 699,
      image: "",
    },
    {
      id: 2,
      name: "Laptop Pro 15",
      prevPrice: 1399,
      currPrice: 1299,
      image: "https://via.placeholder.com/150?text=Laptop+Pro+15",
    },
    {
      id: 3,
      name: "Wireless Earbuds Z",
      prevPrice: 199,
      currPrice: 149,
      image: "https://via.placeholder.com/150?text=Wireless+Earbuds+Z",
    },
    {
      id: 4,
      name: 'Smart TV 50"',
      prevPrice: 899,
      currPrice: 799,
      image: "https://via.placeholder.com/150?text=Smart+TV+50",
    },
    {
      id: 5,
      name: "Gaming Console 5",
      prevPrice: 599,
      currPrice: 499,
      image: "https://via.placeholder.com/150?text=Gaming+Console+5",
    },
    {
      id: 6,
      name: "Bluetooth Speaker Mini",
      prevPrice: 129,
      currPrice: 99,
      image: "https://via.placeholder.com/150?text=Bluetooth+Speaker+Mini",
    },
    {
      id: 7,
      name: "4K Action Camera",
      prevPrice: 349,
      currPrice: 299,
      image: "https://via.placeholder.com/150?text=4K+Action+Camera",
    },
    {
      id: 8,
      name: "Smartwatch Elite",
      prevPrice: 249,
      currPrice: 199,
      image: "https://via.placeholder.com/150?text=Smartwatch+Elite",
    },
    {
      id: 9,
      name: "Gaming Headset X",
      prevPrice: 129,
      currPrice: 89,
      image: "https://via.placeholder.com/150?text=Gaming+Headset+X",
    },
    {
      id: 10,
      name: "External SSD 1TB",
      prevPrice: 199,
      currPrice: 149,
      image: "https://via.placeholder.com/150?text=External+SSD+1TB",
    },
    {
      id: 11,
      name: "Drone Phantom",
      prevPrice: 999,
      currPrice: 899,
      image: "https://via.placeholder.com/150?text=Drone+Phantom",
    },
    {
      id: 12,
      name: "Digital Camera HD",
      prevPrice: 599,
      currPrice: 549,
      image: "https://via.placeholder.com/150?text=Digital+Camera+HD",
    },
    {
      id: 13,
      name: "Portable Charger 20k",
      prevPrice: 79,
      currPrice: 59,
      image: "https://via.placeholder.com/150?text=Portable+Charger+20k",
    },
    {
      id: 14,
      name: "VR Headset Pro",
      prevPrice: 399,
      currPrice: 349,
      image: "https://via.placeholder.com/150?text=VR+Headset+Pro",
    },
    {
      id: 15,
      name: 'Tablet 10.1"',
      prevPrice: 449,
      currPrice: 399,
      image: "https://via.placeholder.com/150?text=Tablet+10.1",
    },
    {
      id: 16,
      name: "Wireless Keyboard",
      prevPrice: 69,
      currPrice: 49,
      image: "https://via.placeholder.com/150?text=Wireless+Keyboard",
    },
    {
      id: 17,
      name: "Noise-Cancelling Headphones",
      prevPrice: 299,
      currPrice: 249,
      image: "https://via.placeholder.com/150?text=Noise-Cancelling+Headphones",
    },
    {
      id: 18,
      name: "Smart Home Speaker",
      prevPrice: 159,
      currPrice: 129,
      image: "https://via.placeholder.com/150?text=Smart+Home+Speaker",
    },
    {
      id: 19,
      name: "Projector 1080p",
      prevPrice: 649,
      currPrice: 599,
      image: "https://via.placeholder.com/150?text=Projector+1080p",
    },
    {
      id: 20,
      name: "Fitness Tracker X",
      prevPrice: 99,
      currPrice: 79,
      image: "https://via.placeholder.com/150?text=Fitness+Tracker+X",
    },
  ];
  
  export default products;